version: '3'

tasks:
    run:
        cmds:
            - task lint
            - task compile
            - powershell start out/executable.exe
    compile:
        cmds:
            - powershell New-Item -ItemType Directory -Force -Path out/
            - gcc -o out/executable.exe src/main.c
    lint:
        cmds:
            - cpplint --config="cpplint.cfg" main.c