version: "3.17"

vars:
    fileName: main.c
    executableName: executable

tasks:
    run:
        aliases: [dev]
        deps: [lint, compile]
        desc: 
            Lint, compiles and runs a c file
        cmds:
            - out/"{{.executableName}}".exe

    compile:
        aliases: [build]
        desc:
            Creates an out folder if it doesn't exist and then creates a developer binary
        cmds:
            - powershell md -Force out/ | powershell Out-Null
            - task: kill
            - ccache gcc -o out/"{{.executableName}}".exe src/"{{.fileName}}" -O0

    kill:
        desc:
            Kills previous binary if its open
        cmds:
            - powershell taskkill /f /im "{{.executableName}}" | powershell Out-Null
        silent: true
    
    dist:
        desc:
            Creates an optimised output binary
        cmds:
            - powershell md -Force dist/ | powershell Out-Null
            - ccache gcc -o dist/"{{.executableName}}".exe src/"{{.fileName}}" -O2
    
    compress:
        aliases: [comp]
        desc:
            Creates a low file size output binary
        cmds:
            - powershell md -Force dist/ | powershell Out-Null
            - ccache gcc -o dist/"{{.executableName}}".upx.exe src/"{{.fileName}}" -Os
            - upx --best dist/"{{.executableName}}".upx.exe
        
    lint:
        desc:
            Lints the c file with cpplint and the cpplint.cfg file
        cmds:
            - cpplint src/"{{.fileName}}"
