version: '3'

vars:
    fileName: main.c
    executableName: executable.exe

tasks:
    run:
        desc: 
            Lint, compiles and runs a c file
        cmds:
            - task lint
            - task compile
            - powershell start out/"{{.executableName}}"

    compile:
        desc:
            Creates an out folder if it doesn't exist and then runs the GCC compiler
        cmds:
            - powershell md -Force out/ | powershell Out-Null
            - gcc -o out/"{{.executableName}}" src/"{{.fileName}}"

    lint:
        desc:
            Lints the c file with cpplint and the cpplint.cfg file
        cmds:
            - cpplint src/"{{.fileName}}"
